# Generated by Django 5.2.11 on 2026-02-13 17:38

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Route',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_location', models.CharField(max_length=255)),
                ('end_location', models.CharField(max_length=255)),
                ('total_distance_miles', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_fuel_cost', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)])),
                ('total_gallons_needed', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('route_polyline', models.TextField(blank=True)),
                ('fuel_efficiency_mpg', models.DecimalField(decimal_places=2, default=10.0, max_digits=5)),
                ('tank_range_miles', models.DecimalField(decimal_places=2, default=500.0, max_digits=6)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FuelStation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opis_id', models.IntegerField(db_index=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('address', models.CharField(max_length=255)),
                ('city', models.CharField(db_index=True, max_length=100)),
                ('state', models.CharField(db_index=True, max_length=2)),
                ('rack_id', models.IntegerField()),
                ('retail_price', models.DecimalField(decimal_places=5, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, db_index=True, decimal_places=7, max_digits=10, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['retail_price'],
                'indexes': [models.Index(fields=['state', 'retail_price'], name='api_fuelsta_state_c0ca60_idx'), models.Index(fields=['latitude', 'longitude'], name='api_fuelsta_latitud_a8079e_idx')],
            },
        ),
        migrations.CreateModel(
            name='FuelStop',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('stop_order', models.PositiveIntegerField()),
                ('distance_from_start_miles', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('gallons_to_fill', models.DecimalField(decimal_places=2, max_digits=6, validators=[django.core.validators.MinValueValidator(0)])),
                ('cost_at_stop', models.DecimalField(decimal_places=2, max_digits=8, validators=[django.core.validators.MinValueValidator(0)])),
                ('latitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=7, max_digits=10)),
                ('fuel_station', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.fuelstation')),
                ('route', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fuel_stops', to='api.route')),
            ],
            options={
                'ordering': ['route', 'stop_order'],
                'unique_together': {('route', 'stop_order')},
            },
        ),
    ]
