# Generated by Django 5.1.6 on 2026-02-13 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fuelstation',
            name='opis_id',
            field=models.IntegerField(db_index=True),
        ),
    ]
